### PR TITLE
Formidable events

### PR DESCRIPTION
**Pull request by Eomm**
This PR add the functionality of listen the events emitted by formidable and manage the case when multiple express-formidable are added to the middleware chain.

Let me know if it is ok.
Thank you

### CODE REVIEW

**Comment by Eomm** [comment]
Hello @utatti,
what do you think about this PR?
Let me know 

Thank you very much

**Review by hatashiro — APPROVED** [review]
LGTM

**Review by hatashiro — APPROVED** [review]

**Review by hatashiro — APPROVED** [review]

**Review by hatashiro — APPROVED** [review]

**Review by hatashiro — APPROVED** [review]
Looks good! Sorry I've been busy recently.

**Review by hatashiro — APPROVED** [review]
Looks good! Sorry I've been busy recently.

**Review by hatashiro — APPROVED** [review]
Looks good! Sorry I've been busy recently.

**Comment by hatashiro** [comment]
So this is the result of 5 hours of GitHub outage.

**Comment by Eomm** [comment]
Thank you, glad to be merged 😄

**Comment by Prinzhorn** [comment]
I think this is leaking memory, because the event handlers are never removed, which prevents `form` from ever getting garbage collected. But I didn't dig into it.

**Pull request merged**
